ALTER TABLE `leadership_members` MODIFY COLUMN `memberType` enum('board','member','advisor') NOT NULL;
--> statement-breakpoint
UPDATE `leadership_members` SET `imageUrl` = 'https://cxjy0gqflcaufkda.public.blob.vercel-storage.com/abhiara-images/leadership/2026-09-28T13-44-23-476Z-biswajita-mallik.webp' WHERE `memberType` = 'board' AND `nameEn` = 'Biswajita Mallik';
--> statement-breakpoint
INSERT INTO `leadership_members` (`memberType`,`nameEn`,`nameOd`,`roleEn`,`roleOd`,`qualificationEn`,`qualificationOd`,`bioEn`,`bioOd`,`imageUrl`,`profileUrl`,`isPublished`,`sortOrder`) SELECT 'member','Umakanta Mahanta',NULL,'Chief Operating Officer, Odisha','ମୁଖ୍ୟ ପରିଚାଳନା ଅଧିକାରୀ, ଓଡ଼ିଶା',NULL,NULL,'Supports operational coordination for the Foundation in Odisha.','ଓଡ଼ିଶାରେ ଫାଉଣ୍ଡେସନର ପରିଚାଳନା ସମନ୍ୱୟରେ ସହଯୋଗ କରନ୍ତି।','https://cxjy0gqflcaufkda.public.blob.vercel-storage.com/abhiara-images/leadership/2026-09-28T13-43-36-409Z-umakanta-mahanta.png',NULL,1,30 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `leadership_members` WHERE `nameEn`='Umakanta Mahanta');
--> statement-breakpoint
INSERT INTO `leadership_members` (`memberType`,`nameEn`,`nameOd`,`roleEn`,`roleOd`,`qualificationEn`,`qualificationOd`,`bioEn`,`bioOd`,`imageUrl`,`profileUrl`,`isPublished`,`sortOrder`) SELECT 'member','Gouranga Charan Sahoo','ଗୌରାଙ୍ଗ ଚରଣ ସାହୁ','Member','ସଦସ୍ୟ','B.Com, Master of Commerce','ବି.କମ୍, ମାଷ୍ଟର ଅଫ୍ କମର୍ସ',NULL,NULL,'https://cxjy0gqflcaufkda.public.blob.vercel-storage.com/abhiara-images/leadership/2026-09-28T13-43-00-715Z-gouranga-charan-sahoo.jpg',NULL,1,40 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `leadership_members` WHERE `nameEn`='Gouranga Charan Sahoo');
--> statement-breakpoint
INSERT INTO `leadership_members` (`memberType`,`nameEn`,`nameOd`,`roleEn`,`roleOd`,`qualificationEn`,`qualificationOd`,`bioEn`,`bioOd`,`imageUrl`,`profileUrl`,`isPublished`,`sortOrder`) SELECT 'member','Mr. Gurpreetsingh Nebhrani',NULL,'Ground Support and Statutory Compliance','କ୍ଷେତ୍ର ସହଯୋଗ ଓ ବିଧିବଦ୍ଧ ଅନୁପାଳନ','Chartered Accountant, CFA Level 2','ଚାର୍ଟାର୍ଡ ଆକାଉଣ୍ଟାଣ୍ଟ, CFA Level 2','Based in Mumbai and supports ground work and statutory compliance.','ମୁମ୍ବାଇରେ ଆଧାରିତ ଏବଂ କ୍ଷେତ୍ର କାମ ଓ ବିଧିବଦ୍ଧ ଅନୁପାଳନରେ ସହଯୋଗ କରନ୍ତି।','https://cxjy0gqflcaufkda.public.blob.vercel-storage.com/abhiara-images/leadership/2026-09-28T13-43-07-904Z-gurpreetsingh-nebhrani.jpg',NULL,1,50 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `leadership_members` WHERE `nameEn`='Mr. Gurpreetsingh Nebhrani');
--> statement-breakpoint
INSERT INTO `leadership_members` (`memberType`,`nameEn`,`nameOd`,`roleEn`,`roleOd`,`qualificationEn`,`qualificationOd`,`bioEn`,`bioOd`,`imageUrl`,`profileUrl`,`isPublished`,`sortOrder`) SELECT 'member','CA Asis Kumar Samal',NULL,'Member and Ground Support','ସଦସ୍ୟ ଓ କ୍ଷେତ୍ର ସହଯୋଗ','Chartered Accountant','ଚାର୍ଟାର୍ଡ ଆକାଉଣ୍ଟାଣ୍ଟ','Based in Thane, Maharashtra, with roots in Kendrapara, Odisha. Supports ground level programme work.','ମହାରାଷ୍ଟ୍ରର ଠାଣେରେ ରହୁଛନ୍ତି ଏବଂ ଓଡ଼ିଶାର କେନ୍ଦ୍ରାପଡ଼ା ସହିତ ମୂଳ ସମ୍ପର୍କ ରହିଛି। କ୍ଷେତ୍ର ସ୍ତରର କାର୍ଯ୍ୟକ୍ରମରେ ସହଯୋଗ କରନ୍ତି।','https://cxjy0gqflcaufkda.public.blob.vercel-storage.com/abhiara-images/leadership/2026-09-28T13-43-11-849Z-asis-kumar-samal.jpg',NULL,1,60 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `leadership_members` WHERE `nameEn`='CA Asis Kumar Samal');
--> statement-breakpoint
INSERT INTO `leadership_members` (`memberType`,`nameEn`,`nameOd`,`roleEn`,`roleOd`,`qualificationEn`,`qualificationOd`,`bioEn`,`bioOd`,`imageUrl`,`profileUrl`,`isPublished`,`sortOrder`) SELECT 'member','Prasant Behera',NULL,'Member and Ground Support','ସଦସ୍ୟ ଓ କ୍ଷେତ୍ର ସହଯୋଗ','B.Com, CMA Finalist','ବି.କମ୍, CMA ଫାଇନାଲିଷ୍ଟ','Based in Bhubaneswar, Odisha, and supports ground level programme work.','ଭୁବନେଶ୍ୱର, ଓଡ଼ିଶାରେ ଆଧାରିତ ଏବଂ କ୍ଷେତ୍ର ସ୍ତରର କାର୍ଯ୍ୟକ୍ରମରେ ସହଯୋଗ କରନ୍ତି।','https://cxjy0gqflcaufkda.public.blob.vercel-storage.com/abhiara-images/leadership/2026-09-28T13-43-16-782Z-prasant-behera.jpg',NULL,1,70 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `leadership_members` WHERE `nameEn`='Prasant Behera');
--> statement-breakpoint
INSERT INTO `leadership_members` (`memberType`,`nameEn`,`nameOd`,`roleEn`,`roleOd`,`qualificationEn`,`qualificationOd`,`bioEn`,`bioOd`,`imageUrl`,`profileUrl`,`isPublished`,`sortOrder`) SELECT 'member','Samiksha Parekh',NULL,'Advocate and Consultant','ଆଇନଜୀବୀ ଓ ପରାମର୍ଶଦାତା',NULL,NULL,'Based in Mumbai. Advises the Foundation on responsible systems, CSR readiness and organisational compliance.','ମୁମ୍ବାଇରେ ଆଧାରିତ। ଦାୟିତ୍ୱପୂର୍ଣ୍ଣ ବ୍ୟବସ୍ଥା, CSR ପ୍ରସ୍ତୁତି ଓ ସଂଗଠନୀୟ ଅନୁପାଳନ ବିଷୟରେ ଫାଉଣ୍ଡେସନକୁ ପରାମର୍ଶ ଦିଅନ୍ତି।','https://cxjy0gqflcaufkda.public.blob.vercel-storage.com/abhiara-images/leadership/2026-09-28T13-43-21-476Z-samiksha-parekh.png',NULL,1,80 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `leadership_members` WHERE `nameEn`='Samiksha Parekh');
--> statement-breakpoint
INSERT INTO `leadership_members` (`memberType`,`nameEn`,`nameOd`,`roleEn`,`roleOd`,`qualificationEn`,`qualificationOd`,`bioEn`,`bioOd`,`imageUrl`,`profileUrl`,`isPublished`,`sortOrder`) SELECT 'member','Advocate Farheen Ansari',NULL,'Secretarial and Legal Support','ସଚିବୀୟ ଓ ଆଇନଗତ ସହଯୋଗ','Advocate','ଆଇନଜୀବୀ','Supports the Foundation with secretarial and legal work.','ଫାଉଣ୍ଡେସନର ସଚିବୀୟ ଓ ଆଇନଗତ କାମରେ ସହଯୋଗ କରନ୍ତି।','https://cxjy0gqflcaufkda.public.blob.vercel-storage.com/abhiara-images/leadership/2026-09-28T13-43-28-531Z-farheen-ansari.png',NULL,1,90 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `leadership_members` WHERE `nameEn`='Advocate Farheen Ansari');
--> statement-breakpoint
INSERT INTO `leadership_members` (`memberType`,`nameEn`,`nameOd`,`roleEn`,`roleOd`,`qualificationEn`,`qualificationOd`,`bioEn`,`bioOd`,`imageUrl`,`profileUrl`,`isPublished`,`sortOrder`) SELECT 'member','Rajkumar Mallik','ରାଜକୁମାର ମଲ୍ଲିକ','Core Team Member','ମୁଖ୍ୟ ଦଳ ସଦସ୍ୟ',NULL,NULL,'Supports community service and education activities.','ସମୁଦାୟ ସେବା ଓ ଶିକ୍ଷା କାର୍ଯ୍ୟରେ ସହଯୋଗ କରନ୍ତି।',NULL,NULL,1,91 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `leadership_members` WHERE `nameEn`='Rajkumar Mallik');
--> statement-breakpoint
INSERT INTO `leadership_members` (`memberType`,`nameEn`,`nameOd`,`roleEn`,`roleOd`,`qualificationEn`,`qualificationOd`,`bioEn`,`bioOd`,`imageUrl`,`profileUrl`,`isPublished`,`sortOrder`) SELECT 'member','Alok Behera','ଆଲୋକ ବେହେରା','Core Team Member','ମୁଖ୍ୟ ଦଳ ସଦସ୍ୟ',NULL,NULL,'Supports education and community activities.','ଶିକ୍ଷା ଓ ସମୁଦାୟ କାର୍ଯ୍ୟରେ ସହଯୋଗ କରନ୍ତି।',NULL,NULL,1,92 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `leadership_members` WHERE `nameEn`='Alok Behera');
--> statement-breakpoint
INSERT INTO `leadership_members` (`memberType`,`nameEn`,`nameOd`,`roleEn`,`roleOd`,`qualificationEn`,`qualificationOd`,`bioEn`,`bioOd`,`imageUrl`,`profileUrl`,`isPublished`,`sortOrder`) SELECT 'member','Ashish (Rocky)','ଆଶିଷ (ରକି)','Core Team Member','ମୁଖ୍ୟ ଦଳ ସଦସ୍ୟ',NULL,NULL,'Supports community service and ground level activities.','ସମୁଦାୟ ସେବା ଓ କ୍ଷେତ୍ର କାର୍ଯ୍ୟରେ ସହଯୋଗ କରନ୍ତି।',NULL,NULL,1,93 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `leadership_members` WHERE `nameEn`='Ashish (Rocky)');
--> statement-breakpoint
INSERT INTO `leadership_members` (`memberType`,`nameEn`,`nameOd`,`roleEn`,`roleOd`,`qualificationEn`,`qualificationOd`,`bioEn`,`bioOd`,`imageUrl`,`profileUrl`,`isPublished`,`sortOrder`) SELECT 'member','Manoj Kumar Mallik','ମନୋଜ କୁମାର ମଲ୍ଲିକ','Field Operations','କ୍ଷେତ୍ର ପରିଚାଳନା','MBA in Finance','ଫାଇନାନ୍ସରେ MBA','Coordinates field activities and programme follow up in Odisha.','ଓଡ଼ିଶାରେ କ୍ଷେତ୍ର କାର୍ଯ୍ୟ ଓ କାର୍ଯ୍ୟକ୍ରମ ଅନୁସରଣରେ ସମନ୍ୱୟ କରନ୍ତି।','/images/team-manoj-kumar-mallik.jpeg',NULL,1,94 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `leadership_members` WHERE `nameEn`='Manoj Kumar Mallik');
